version: "3.9"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
    - "27017:27017"
    command: mongod --auth
    environment:
      - MONGO_INITDB_DATABASE=orders
      - MONGO_INITDB_ROOT_USERNAME=anuarserp
      - MONGO_INITDB_ROOT_PASSWORD=password
  server:
    container_name: server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/home/app

volumes:
  mongo-data: